from src.core.config import API_BASE_URL

# Localization strings migrated from MDex.py
STRINGS = {
    "pt-br": {
        "select_language_prompt": "🌍 Selecione o idioma alvo (destino):",
        "selected_language": "Idioma selecionado: {}",
        "manga_title_prompt": "Digite o nome do mangá:",
        "manga_title_empty_error": "⚠️ O título do mangá não pode estar vazio.",
        "search_manga_error": "Erro ao buscar o mangá: {}",
        "no_manga_found": "Nenhum mangá encontrado com o nome: {}",
        "manga_found": "📚 Mangá encontrado: {}",
        "fetching_chapters": "🔍 Buscando capítulos...",
        "available_chapters": "\n📖 Capítulos Disponíveis (Priorizando seu idioma):",
        "chapters_range_prompt": "Capítulos (ex: 1 5 10-20) ou 'all':",
        "downloading_chapter": "📥 Baixando Capítulo {}...",
        "pdf_success": "✅ PDF criado: {}",
        "pdf_error": "⚠️ Erro no PDF do Capítulo {}: {}",
        "ai_prompt_translation": "Deseja ativar Tradução Automática (Omni-Reader para {})? (s/n):",
        "ai_initializing": "🧠 Inicializando Motores de IA (Local)...",
    },
    "en": {
        "select_language_prompt": "🌍 Select target language:",
        "selected_language": "Selected language: {}",
        "manga_title_prompt": "Enter manga name:",
        "manga_title_empty_error": "⚠️ Title cannot be empty.",
        "search_manga_error": "Search error: {}",
        "no_manga_found": "No manga found: {}",
        "manga_found": "📚 Manga found: {}",
        "fetching_chapters": "🔍 Fetching chapters...",
        "available_chapters": "\n📖 Available Chapters (Prioritizing your language):",
        "chapters_range_prompt": "Chapters (e.g. 1 5 10-20) or 'all':",
        "downloading_chapter": "📥 Downloading Chapter {}...",
        "pdf_success": "✅ PDF created: {}",
        "pdf_error": "⚠️ PDF error for Chapter {}: {}",
        "ai_prompt_translation": "Enable Auto-Translation (Omni-Reader for {})? (y/n):",
        "ai_initializing": "🧠 Initializing IA Engines (Local)...",
    },
    "es": {
        "select_language_prompt": "🌍 Seleccione o idioma de destino:",
        "selected_language": "Idioma seleccionado: {}",
        "manga_title_prompt": "Ingrese el nombre del manga:",
        "manga_title_empty_error": "⚠️ El título no pode estar vacío.",
        "search_manga_error": "Error de busca: {}",
        "no_manga_found": "No se encontrou manga: {}",
        "manga_found": "📚 Manga encontrado: {}",
        "fetching_chapters": "🔍 Buscando capítulos...",
        "available_chapters": "\n📖 Capítulos Disponibles (Priorizando su idioma):",
        "chapters_range_prompt": "Capítulos (ej: 1 5 10-20) o 'all':",
        "downloading_chapter": "📥 Descargando Capítulo {}...",
        "pdf_success": "✅ PDF criado: {}",
        "pdf_error": "⚠️ Error en PDF del Capítulo {}: {}",
        "ai_prompt_translation": "¿Activar Traducción Automática (Omni-Reader para {})? (s/n):",
        "ai_initializing": "🧠 Inicializando Motores de IA (Local)...",
    }
}
